import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const NOW = new Date();
const date = (daysAgo: number) => new Date(NOW.getTime() - daysAgo * 86_400_000).toISOString();

const POSTS = [
  // ── BANGKOK (8 posts) ──────────────────────────────────────────────────────
  {
    slug: 'best-temples-bangkok-guide',
    title: 'The 10 Best Temples in Bangkok You Must Visit',
    excerpt: 'From the glittering Grand Palace to the hidden gem of Wat Suthat, discover Bangkok\'s most awe-inspiring temples and how to visit them without the crowds.',
    content: `<h2>Why Bangkok's Temples Are Unmissable</h2><p>Bangkok is home to over 400 Buddhist temples, locally called <em>wats</em>. Each one tells a different story about Thai history, religion, and culture. Whether you are a first-time visitor or a seasoned traveller, the temple circuit in Bangkok never gets old.</p><h2>1. Wat Phra Kaew (Temple of the Emerald Buddha)</h2><p>Located inside the Grand Palace complex, this is the most sacred Buddhist temple in Thailand. The Emerald Buddha — actually carved from jade — sits high on a golden throne. Dress code is strict: cover shoulders and knees, or borrow a sarong at the entrance.</p><h2>2. Wat Pho (Temple of the Reclining Buddha)</h2><p>Just a short walk from the Grand Palace, Wat Pho is home to the famous 46-metre long reclining Buddha covered in gold leaf. The temple complex is also the birthplace of traditional Thai massage — you can book a session right on site.</p><h2>3. Wat Arun (Temple of Dawn)</h2><p>Best viewed from across the Chao Phraya River at sunset, Wat Arun's spires are encrusted with colourful porcelain and seashells. Climb the steep steps for panoramic views of the river and the Bangkok skyline.</p><h2>4. Wat Saket (Golden Mount)</h2><p>Perched on an artificial hill, this temple offers 360-degree views of old Bangkok from the top. The climb is 318 steps but the view is absolutely worth it, especially in the early morning.</p><h2>5. Wat Benchamabophit (Marble Temple)</h2><p>Built from Italian Carrara marble during the reign of King Rama V, this is one of Bangkok's most photogenic temples. Come early morning to watch monks receive alms offerings along the canal.</p><h2>Practical Tips</h2><p>Visit temples between 8am and 11am to avoid peak heat and tour groups. Carry a light scarf for cover. Combine Wat Phra Kaew, Wat Pho and Wat Arun in a single morning by taking the Chao Phraya Express Boat.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['temples', 'culture', 'Bangkok', 'sightseeing'],
    readingTimeMin: 7,
    publishedAt: date(2),
  },
  {
    slug: 'bangkok-street-food-guide',
    title: 'Bangkok Street Food: The Ultimate Guide to Eating Like a Local',
    excerpt: 'Pad thai, mango sticky rice, boat noodles — Bangkok\'s street food scene is legendary. Here\'s exactly where to go, what to order, and how much to pay.',
    content: `<h2>Bangkok's Street Food Culture</h2><p>Bangkok is consistently ranked as one of the world's best cities for street food. The city never sleeps, and neither do its food stalls. From pre-dawn markets to late-night carts, there is always something delicious within walking distance.</p><h2>Yaowarat (Chinatown)</h2><p>Yaowarat Road is Bangkok's most famous street food destination. Come after 6pm when the stalls set up and the street fills with the smell of roasting seafood and sizzling noodles. Must-try: barbecued pork, braised duck, and mango sorbet.</p><h2>Or Tor Kor Market</h2><p>Considered the cleanest and most high-quality fresh market in Bangkok, Or Tor Kor is next to Chatuchak Weekend Market. It's a great place to try prepared Thai dishes, exotic fruits, and premium dried goods.</p><h2>Victory Monument Area</h2><p>The streets around Victory Monument are packed with boat noodle stalls. A bowl costs 15–30 baht and the broth is deeply rich and flavourful. It's a local favourite for lunch.</p><h2>What to Order</h2><ul><li>Pad Thai: stir-fried rice noodles with egg, tofu and peanuts</li><li>Som Tum: green papaya salad with chilli and lime</li><li>Mango Sticky Rice: ripe mango with coconut sticky rice</li><li>Boat Noodles: rich pork or beef broth noodles in a small bowl</li><li>Grilled Pork Skewers (Moo Ping): sweet marinated pork on bamboo skewers</li></ul><h2>Budget Guide</h2><p>Street food in Bangkok is extraordinarily affordable. A full meal from a street stall typically costs 50–120 baht (£1.10–£2.70). Budget 300 baht per day for street food and you will eat very well indeed.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['street food', 'food', 'Bangkok', 'local tips'],
    readingTimeMin: 6,
    publishedAt: date(5),
  },
  {
    slug: 'bangkok-airport-transfer-guide',
    title: 'Bangkok Airport Transfer Guide: Suvarnabhumi vs Don Mueang',
    excerpt: 'Landing in Bangkok? Here\'s everything you need to know about getting from both airports into the city — and which transfer option is best for your trip.',
    content: `<h2>Bangkok's Two Airports</h2><p>Bangkok has two international airports: Suvarnabhumi (BKK) and Don Mueang (DMK). Understanding which one you're arriving at is the first step to planning your transfer.</p><h2>Suvarnabhumi Airport (BKK)</h2><p>Suvarnabhumi is the main international hub, handling most long-haul flights from Europe, the Americas and the Middle East. It's located 30km east of the city centre.</p><h3>Transfer Options from Suvarnabhumi</h3><ul><li><strong>Airport Rail Link:</strong> Fast, cheap (45 baht), runs to Phaya Thai in 30 minutes — but no luggage racks and gets crowded</li><li><strong>Metered Taxi:</strong> 250–350 baht plus 50 baht expressway toll. Join the official queue on Level 1.</li><li><strong>Private Transfer:</strong> Fixed price, air-conditioned, driver meets you at arrivals. Best option for families or heavy luggage.</li></ul><h2>Don Mueang Airport (DMK)</h2><p>Don Mueang is the low-cost carrier hub (AirAsia, Nok Air, Lion Air). It's 24km north of the city centre.</p><h3>Transfer Options from Don Mueang</h3><ul><li><strong>Bus A1/A2:</strong> Cheapest option (30 baht) to Mo Chit BTS. Takes 45–90 minutes depending on traffic.</li><li><strong>Metered Taxi:</strong> 200–300 baht plus toll. Fastest option when traffic is light.</li><li><strong>Private Transfer:</strong> Recommended for early morning or late-night arrivals when public transport is limited.</li></ul><h2>Which Is Better: Taxi or Private Transfer?</h2><p>Taxis are fine if you're travelling solo with light luggage and speak some Thai. Private transfers are better for families, early/late arrivals, and anyone who wants a stress-free start to their holiday. With Werest, you get a fixed price, a meet-and-greet service, and no hidden charges.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['airport transfer', 'Bangkok', 'transport', 'travel tips'],
    readingTimeMin: 5,
    publishedAt: date(8),
  },
  {
    slug: 'chatuchak-weekend-market-guide',
    title: 'Chatuchak Weekend Market: Your Complete Shopping Guide',
    excerpt: 'With 15,000 stalls and over 200,000 visitors every weekend, Chatuchak is one of the largest markets in the world. Here\'s how to navigate it without losing your mind.',
    content: `<h2>The World's Largest Weekend Market</h2><p>Chatuchak Weekend Market (JJ Market) operates every Saturday and Sunday from 6am to 6pm. It covers 35 acres and houses everything from vintage furniture and antiques to live plants, street food, and handmade clothing.</p><h2>How to Get There</h2><p>Take the BTS Skytrain to Mo Chit station or the MRT to Chatuchak Park. Both stations are a 3-minute walk from the market entrance. Alternatively, book a private transfer from your hotel — Werest can drop you off and pick you up at a set time.</p><h2>Section Map</h2><p>The market is divided into 27 sections. Here are the most important ones:</p><ul><li><strong>Section 2–4:</strong> Vintage clothing, Thai handicrafts, home décor</li><li><strong>Section 7–8:</strong> Plants, flowers, and gardening</li><li><strong>Section 22–26:</strong> Art, ceramics, books, antiques</li><li><strong>Food stalls:</strong> Scattered throughout, but concentrated in Sections 4 and 6</li></ul><h2>Shopping Tips</h2><ul><li>Go early (8–10am) to avoid the worst heat and crowds</li><li>Bring cash — most stalls don't accept cards</li><li>Bargaining is expected, but do it respectfully</li><li>Wear light clothing and comfortable shoes</li><li>Download the Chatuchak map app for iOS or Android</li></ul><h2>What to Buy</h2><p>Chatuchak is best for: handmade jewellery, Thai silk, ceramics, vintage streetwear, Buddha statues, wooden furniture, and tropical plants. Avoid buying wildlife (illegal) or electronics (counterfeits).</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1555217851-6141535bd771?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['shopping', 'markets', 'Bangkok', 'weekend'],
    readingTimeMin: 5,
    publishedAt: date(12),
  },
  {
    slug: 'bangkok-rooftop-bars-guide',
    title: 'Best Rooftop Bars in Bangkok for Sunset Drinks',
    excerpt: 'Bangkok\'s skyline is spectacular at sunset. These rooftop bars offer the best views of the city — from iconic skyscraper venues to hidden neighbourhood gems.',
    content: `<h2>Bangkok's Rooftop Bar Scene</h2><p>Bangkok has developed one of Asia's best rooftop bar scenes over the past decade. Whether you want a dressy night out or a casual beer with a view, there's a spot for every budget.</p><h2>Top Picks</h2><h3>Vertigo & Moon Bar — Banyan Tree</h3><p>At 61 floors, Vertigo is one of Bangkok's highest open-air bars. No roof — just open sky and 360-degree views. Smart-casual dress code. Budget 800–1,500 baht per person for drinks.</p><h3>Sky Bar — Lebua at State Tower</h3><p>Made famous by The Hangover Part II, the circular Sky Bar juts out from the building like the prow of a ship. At 247 metres, the view is breathtaking. Expect to spend 1,000–2,000 baht for cocktails.</p><h3>SEEN Bangkok — Avani+ Riverside</h3><p>On the west bank of the Chao Phraya, SEEN offers a more relaxed vibe with great views of the river and Bangkok skyline. More affordable than the Silom options.</p><h3>Octave Rooftop Lounge — Marriott Sukhumvit</h3><p>Spanning three floors (45–49), Octave is popular with younger crowds and has competitive happy-hour pricing. Great views of the Sukhumvit skyline.</p><h2>Practical Notes</h2><p>Most rooftop bars have a smart-casual dress code — no shorts or flip-flops. Some charge a minimum spend (usually 600–1,000 baht). Go at 5:30pm to secure a good spot before sunset at around 6:15pm.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['nightlife', 'bars', 'Bangkok', 'sunset', 'views'],
    readingTimeMin: 5,
    publishedAt: date(18),
  },
  {
    slug: 'bangkok-day-trips-from-city',
    title: '7 Best Day Trips from Bangkok (With Transfer Times)',
    excerpt: 'Bangkok makes an excellent base for exploring Central Thailand. These seven destinations are all reachable in under 3 hours by private transfer.',
    content: `<h2>Why Bangkok is a Perfect Base</h2><p>Bangkok's central location and excellent road network make it ideal for day trips. With a private transfer, you can reach many world-class destinations, spend 4–6 hours exploring, and be back in your hotel by evening.</p><h2>1. Ayutthaya — 1.5 hours</h2><p>Thailand's former capital and a UNESCO World Heritage Site. Hundreds of ancient temples, towering prangs, and the famous Buddha head entwined in tree roots. Best visited by hiring a tuk-tuk or bicycle on arrival.</p><h2>2. Damnoen Saduak Floating Market — 1.5 hours</h2><p>The most iconic floating market in Thailand. Best before 9am. Combine with the Maeklong Railway Market in the same day trip.</p><h2>3. Kanchanaburi — 2.5 hours</h2><p>Home to the Bridge on the River Kwai and moving WWII memorials. The Death Railway runs through stunning jungle scenery. A sobering but important historical destination.</p><h2>4. Khao Yai National Park — 2 hours</h2><p>Thailand's oldest national park, a UNESCO World Heritage Site. Elephants, gibbons, hornbills and waterfalls. Best for nature lovers and photographers.</p><h2>5. Pattaya — 1.5–2 hours</h2><p>Thailand's most famous beach resort town. Beaches, water parks, golf courses, and the spectacular Sanctuary of Truth wooden temple.</p><h2>6. Hua Hin — 2.5 hours</h2><p>The royal retreat. Quiet, elegant beaches, golf courses, and excellent fresh seafood. Very different from Pattaya — more relaxed and family-friendly.</p><h2>7. Samut Songkhram — 1 hour</h2><p>A quiet riverside town with canal-side homestays, coconut farms, and the stunning Mae Klong (Maeklong) market. Great for those wanting to see rural Thailand without going far.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['day trips', 'Bangkok', 'Ayutthaya', 'transport'],
    readingTimeMin: 6,
    publishedAt: date(22),
  },
  {
    slug: 'bangkok-neighborhoods-guide',
    title: 'Bangkok Neighborhoods: Which Area Should You Stay In?',
    excerpt: 'Sukhumvit, Silom, Riverside, Old Town — every Bangkok neighborhood has a completely different vibe. Here\'s how to choose the right one for your trip.',
    content: `<h2>Bangkok's Main Districts</h2><p>Bangkok is a massive city with very distinct neighborhoods. Choosing where to stay will significantly affect your experience of the city.</p><h2>Sukhumvit</h2><p>Bangkok's most international district, stretching from Nana to On Nut. Excellent transport (BTS), world-class restaurants, rooftop bars, and everything from budget guesthouses to five-star hotels. Best for: first-timers, party goers, business travellers.</p><h2>Silom / Sathon</h2><p>The financial district by day, buzzing bar strip by night. Patpong Night Market is here, as are some of Bangkok's finest restaurants. Easy access to Lumphini Park. Best for: those who want to combine business and pleasure.</p><h2>Riverside / Charoen Krung</h2><p>The old trading district along the Chao Phraya River. Grand colonial-era hotels (Mandarin Oriental, Capella), creative arts district TCDC, and excellent river access. Best for: honeymooners, heritage seekers, luxury travellers.</p><h2>Rattanakosin (Old Town)</h2><p>The historic heart of Bangkok. Walking distance to the Grand Palace, Wat Pho, Khao San Road. Budget accommodation dominates. Best for: backpackers, temple enthusiasts, cultural immersion.</p><h2>Ari / Phaya Thai</h2><p>Quieter, more residential. Loved by expats and long-stay travellers. Excellent coffee shops, local restaurants, and a relaxed atmosphere away from the tourist trail.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['accommodation', 'Bangkok', 'neighborhoods', 'where to stay'],
    readingTimeMin: 6,
    publishedAt: date(30),
  },
  {
    slug: 'grand-palace-bangkok-visit-guide',
    title: 'Visiting the Grand Palace Bangkok: Everything You Need to Know',
    excerpt: 'The Grand Palace is Bangkok\'s most visited attraction. Beat the crowds, avoid the scams, and make the most of your visit with this complete guide.',
    content: `<h2>About the Grand Palace</h2><p>Built in 1782 as the official residence of the Kings of Thailand, the Grand Palace complex covers 218,000 square metres and contains dozens of buildings, halls, and pavilions. It remains the spiritual heart of Bangkok.</p><h2>Opening Hours & Tickets</h2><p>Open daily 8:30am–3:30pm (last entry). Admission: 500 baht (includes entry to Wat Phra Kaew). Closed during royal ceremonies — check the official website before visiting.</p><h2>Dress Code (Strictly Enforced)</h2><p>Shoulders and knees must be covered. Sleeveless tops, shorts, short skirts, and tight trousers are not permitted. Free sarong loans are available at the entrance gate if you forget.</p><h2>The Scam to Watch Out For</h2><p>Tuk-tuk drivers near the entrance sometimes tell tourists "The Palace is closed today" and offer to take them on an alternative tour. The Palace is almost never closed. Walk past and enter through the official ticket gate.</p><h2>Best Time to Visit</h2><p>Arrive at opening (8:30am) for the smallest crowds. The complex becomes extremely busy between 10am and 2pm, especially with tour groups. Allow 2–3 hours for a thorough visit.</p><h2>What to See Inside</h2><ul><li>Wat Phra Kaew (Temple of the Emerald Buddha) — unmissable</li><li>Royal Pantheon — statues of all Chakri kings</li><li>Phra Mondop (Royal Library)</li><li>Chakri Maha Prasat Hall</li><li>Ramakien murals — 178 panels depicting the Thai epic</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1200&q=80',
    category: 'BANGKOK',
    tags: ['Grand Palace', 'Bangkok', 'temples', 'tourist tips'],
    readingTimeMin: 5,
    publishedAt: date(35),
  },

  // ── PHUKET (7 posts) ────────────────────────────────────────────────────────
  {
    slug: 'best-beaches-phuket-guide',
    title: 'Best Beaches in Phuket: A Complete Island Guide',
    excerpt: 'Patong, Kata, Kamala, Nai Harn — Phuket has over 30 beaches and they are all very different. Here\'s how to find the right one for your trip.',
    content: `<h2>Phuket's Beach Diversity</h2><p>Phuket's west coast beaches are the most famous and most visited. The east coast is calmer but less scenic. Each beach has its own personality — from the full-moon-party energy of Patong to the zen quietude of Nai Harn.</p><h2>Patong Beach</h2><p>The most famous and most developed. 3km of golden sand, water sports, beach clubs, and the Bangla Road nightlife strip behind it. Best for: party-goers, first-timers, those who want everything on the doorstep.</p><h2>Kata Beach</h2><p>More relaxed than Patong but still has good restaurants, surf schools, and resort hotels. Two bays — Kata Yai and Kata Noi. Best for: families, couples, beginner surfers.</p><h2>Kamala Beach</h2><p>Quieter, more local-feeling. No mega resorts or Bangla Road. Beach clubs (Café del Mar, Catch Beach Club) attract a more upmarket crowd. Best for: those who want beach clubs without the party scene.</p><h2>Nai Harn Beach</h2><p>The most beautiful beach in Phuket, in the south of the island. Surrounded by hills, calm turquoise water, and a yacht club. No big hotels on the beachfront. Best for: snorkelling, swimming, peaceful mornings.</p><h2>Surin Beach</h2><p>Upmarket, sophisticated. Home to the Amanpuri resort, some of Phuket's best beach restaurants (Bampot, Catch), and a beautiful stretch of sand. Best for: luxury travellers.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1537956965359-7573183d1f57?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['beaches', 'Phuket', 'island', 'swimming'],
    readingTimeMin: 6,
    publishedAt: date(3),
  },
  {
    slug: 'phuket-airport-transfer-guide',
    title: 'Phuket Airport Transfer Guide: How to Get to Your Hotel',
    excerpt: 'Phuket International Airport is on the north end of the island — far from most hotels. Here\'s the fastest, cheapest, and most reliable way to reach your resort.',
    content: `<h2>The Challenge with Phuket Airport</h2><p>Phuket's airport is at the northern tip of the island, while most hotels and beaches are in the south. The distance to Patong Beach is 45km and can take 60–90 minutes by road depending on traffic.</p><h2>Option 1: Private Transfer (Recommended)</h2><p>Book a fixed-price private transfer through Werest Travel. Your driver meets you at arrivals, handles luggage, and takes you directly to your hotel. Fixed pricing means no surge charges — even during peak season.</p><h2>Option 2: Airport Taxi</h2><p>Metered taxis are available from the official taxi counter in the arrivals hall. Fares to Patong: 700–900 baht. Rates are metered but drivers sometimes push fixed higher rates for tourists.</p><h2>Option 3: Minivan Shared Transfer</h2><p>Shared minivans depart when full and stop at multiple hotels. Cost: 180–300 baht per person. Fine for budget travellers, but can be slow if your hotel is last on the route.</p><h2>Option 4: Airport Bus</h2><p>The Smart Bus departs hourly to Patong via Phuket Town. Cost: 100 baht. Takes 90 minutes+. No luggage space. Suited only for very light packers.</p><h2>Our Recommendation</h2><p>For families, couples, or anyone with significant luggage, a private transfer is the best value. The price difference between a private car and a shared minivan is small when you split among 2–4 people, and the comfort difference is significant.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['airport transfer', 'Phuket', 'transport', 'travel tips'],
    readingTimeMin: 5,
    publishedAt: date(7),
  },
  {
    slug: 'phuket-island-hopping-phi-phi',
    title: 'Island Hopping from Phuket: Phi Phi, James Bond Island & More',
    excerpt: 'Phuket is the gateway to some of Thailand\'s most spectacular islands. Here\'s how to plan the perfect island-hopping day trip.',
    content: `<h2>Phuket as Your Island-Hopping Base</h2><p>Phuket's marinas — Chalong Pier, Rassada Pier, Bang Rong Pier — give you access to dozens of islands. Most popular day trips depart at 8am and return by 5pm.</p><h2>Phi Phi Islands</h2><p>Koh Phi Phi Don and Phi Phi Leh are the most famous. Maya Bay (where The Beach was filmed) is on Phi Phi Leh. The trip takes about 90 minutes by speedboat or 2.5 hours by ferry. Day tours typically include snorkelling at Pileh Lagoon, Viking Cave, and Monkey Beach.</p><h2>James Bond Island (Phang Nga Bay)</h2><p>Khao Phing Kan, known as James Bond Island from The Man with the Golden Gun, is in Phang Nga Bay. Usually combined with sea kayaking through mangroves and a visit to a floating Muslim village. Departs from Ao Po Grand Marina.</p><h2>Racha Islands (Raya)</h2><p>Raya Yai and Raya Noi are closer to Phuket (45 minutes by speedboat) and excellent for snorkelling and diving. Calmer seas and clearer water than Phi Phi during high season.</p><h2>Similan Islands</h2><p>The Similans are a 2-hour speedboat journey from Phuket. Open from November to April only. Some of Thailand's best diving — crystal clear water and diverse marine life. Full-day and liveaboard trips available.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['islands', 'Phuket', 'Phi Phi', 'day trips', 'snorkelling'],
    readingTimeMin: 6,
    publishedAt: date(14),
  },
  {
    slug: 'phuket-old-town-guide',
    title: 'Phuket Old Town: A Walking Guide to the Colourful Heritage District',
    excerpt: 'Phuket Old Town\'s Sino-Portuguese architecture, street art, and excellent coffee scene make it one of the most charming neighborhoods in southern Thailand.',
    content: `<h2>About Phuket Old Town</h2><p>Phuket Town's historic centre is a beautifully preserved collection of Sino-Portuguese shophouses built by Chinese merchants during the tin-mining era of the 19th century. The pastel-coloured facades, ornate doorways, and colourful street art make it one of the most photogenic neighbourhoods in Thailand.</p><h2>The Five-Row Houses (Thalang Road)</h2><p>Thalang Road is the oldest street in Phuket Town and the heart of the heritage district. The shophouses here date from the 1880s and house cafes, art galleries, boutique hotels, and independent shops.</p><h2>Must-See Street Art</h2><p>Phuket Old Town has a thriving street art scene. Look for the life-sized painted scenes around Phang Nga Road and Dibuk Road — featuring local residents, fishermen, and historical scenes from the town's past.</p><h2>Best Cafes</h2><ul><li>Draw Cafe — minimal, plants, excellent espresso</li><li>Kopitiam by Wilai — authentic Phuket-style coffee and local snacks</li><li>96 Cafe — Sino-Portuguese interior, great for people-watching</li></ul><h2>Temples and Shrines</h2><p>Don't miss Wat Mongkol Nimit (the most ornate temple in Phuket Town), the Jui Tui Shrine, and the Put Jaw Chinese Temple. The Old Town area is also the centre of Phuket's Chinese Vegetarian Festival in October.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c8dd0d5?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['Phuket Old Town', 'architecture', 'culture', 'walking guide'],
    readingTimeMin: 5,
    publishedAt: date(20),
  },
  {
    slug: 'phuket-luxury-resorts-guide',
    title: 'Best Luxury Resorts in Phuket for 2025',
    excerpt: 'From clifftop infinity pools to private beach villas, these are Phuket\'s finest luxury resorts for an unforgettable tropical escape.',
    content: `<h2>Phuket's Luxury Hotel Scene</h2><p>Phuket has established itself as one of Asia's premier luxury destinations. From the hillside villas of the Andaman coast to the beachfront estates of Surin and Bang Tao, the island offers some of the world's finest resort experiences.</p><h2>Amanpuri — Surin Beach</h2><p>The original Aman in Thailand. 40 Thai-style pavilions on a private headland above Surin Beach. The food, the spa, and the sheer calm of the property are legendary. From £1,200/night.</p><h2>COMO Point Yamu — East Coast</h2><p>Set on a private peninsula on the calmer east coast. Jaw-dropping infinity pool overlooking Phang Nga Bay. Less beach but extraordinary views and exceptional COMO Shambhala spa. From £500/night.</p><h2>Rosewood Phuket — Patong Hills</h2><p>Set on a natural bay with direct beach access. Plunge-pool villas carved into the hillside. Extraordinary sunset views. Some of Phuket's best fine dining. From £650/night.</p><h2>Trisara — Nai Thon</h2><p>Ultra-private and quiet. Every villa has its own private pool and direct ocean access. Very few guests at any time — feels genuinely exclusive. From £800/night.</p><h2>Getting to Your Resort</h2><p>All of Phuket's luxury resorts offer airport transfer services, but these are typically expensive (often 2,000–4,000 baht each way). Booking through Werest gives you the same quality of private transfer at a significantly better price.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['luxury', 'resorts', 'Phuket', 'hotels'],
    readingTimeMin: 6,
    publishedAt: date(28),
  },
  {
    slug: 'phuket-rainy-season-travel-guide',
    title: 'Visiting Phuket in the Rainy Season: What to Expect',
    excerpt: 'May to October is Phuket\'s rainy season, but that doesn\'t mean your holiday will be ruined. Here\'s the honest truth about travelling to Phuket in low season.',
    content: `<h2>Phuket's Two Seasons</h2><p>Phuket has two distinct seasons: high season (November to April) and low season (May to October). The monsoon brings rain from the southwest — but it's rarely all-day rain, and the island has a lot to offer even in the wetter months.</p><h2>What the Rain Is Actually Like</h2><p>Low-season rain in Phuket typically falls in short, heavy bursts — usually in the afternoon or evening. Mornings are often clear and sunny. You're unlikely to have all-day rain unless there's a tropical storm. Most activities continue unaffected.</p><h2>What You Can Still Do</h2><ul><li>Beach clubs remain open and are far less crowded</li><li>Phuket Old Town is great in any weather</li><li>Cooking classes, spa treatments, Thai massage</li><li>Big Buddha and Wat Chalong are unaffected by rain</li><li>Phuket FantaSea cultural show</li></ul><h2>What to Avoid</h2><ul><li>Snorkelling on rough days (waves reduce visibility)</li><li>Long boat trips (can be cancelled during storms)</li><li>Similan Islands (officially closed May–October)</li></ul><h2>The Best Reasons to Go in Low Season</h2><p>Prices drop by 30–60%. Crowds disappear. The landscape turns lush and green. Sunsets are spectacular. You can negotiate directly with resorts for excellent rates. For many travellers, low season is actually the best time to visit.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['rainy season', 'Phuket', 'low season', 'travel tips'],
    readingTimeMin: 5,
    publishedAt: date(40),
  },
  {
    slug: 'phuket-local-food-guide',
    title: 'Phuket Local Food: Beyond Pad Thai and Green Curry',
    excerpt: 'Phuket has its own distinct cuisine influenced by Chinese, Malay, and Southern Thai cooking. Here are the dishes you must try — and where to find them.',
    content: `<h2>Phuket's Unique Food Culture</h2><p>Phuket's cuisine reflects its multicultural history. The Chinese merchant community brought hokkien noodles and pork dishes. Malay influence brought rich curries and roti. Southern Thai tradition added powerful heat and local seafood.</p><h2>Mee Hokkien (Phuket Noodles)</h2><p>Thick yellow egg noodles stir-fried with prawns, pork, squid, bean sprouts, and a rich dark soy sauce. Distinctly different from Bangkok-style noodle dishes. Find it at Mee Ton Poe on Phang Nga Road.</p><h2>Oh Tao (Oyster Omelette)</h2><p>A Phuket specialty: a thick, starchy omelette made with oysters and bean sprouts, served with a sweet chilli sauce. Popular at local markets and roadside stalls.</p><h2>Massaman Curry</h2><p>A Southern Thai curry with Muslim-Malay influences. Rich, fragrant, mildly spiced with cinnamon, cardamom, and roasted peanuts. Often made with beef or chicken. Phuket's version is particularly good.</p><h2>Phuket Lobster</h2><p>The waters around Phuket are rich with lobster. Grilled with garlic butter at beachside restaurants, they're extraordinarily fresh. Best found in Rawai, where fishermen land their catch daily.</p><h2>Where to Eat Like a Local</h2><ul><li>Phuket Weekend Night Market (Indy Market): Friday–Sunday evenings in Phuket Town</li><li>Chillva Market: Thursday–Sunday near Thalang Road</li><li>Rawai Seafood Market: fresh seafood at market prices, choose your own and have it cooked nearby</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1569566030073-5a91ca9c1a2a?auto=format&fit=crop&w=1200&q=80',
    category: 'PHUKET',
    tags: ['food', 'Phuket', 'local cuisine', 'restaurants'],
    readingTimeMin: 5,
    publishedAt: date(45),
  },

  // ── PATTAYA (5 posts) ───────────────────────────────────────────────────────
  {
    slug: 'pattaya-sanctuary-of-truth-guide',
    title: 'Sanctuary of Truth Pattaya: The Complete Visitor Guide',
    excerpt: 'The 105-metre all-wood temple on Pattaya\'s beachfront is unlike anything else in Thailand. Here\'s everything you need to know before you visit.',
    content: `<h2>What Is the Sanctuary of Truth?</h2><p>The Sanctuary of Truth is a philosophical monument and cultural landmark built entirely from teak wood — without a single nail or metal fastener. Construction began in 1981 and continues today, as artisans carve new sculptures to replace weathered ones.</p><h2>What to Expect</h2><p>The 105-metre structure is divided into four halls, each dedicated to a different ancient civilisation: Khmer, Chinese, Thai, and Indian. Every surface is covered in intricate hand-carved figures of gods, deities, and mythological creatures.</p><h2>Opening Hours & Tickets</h2><p>Open daily 8am–5pm. Adult ticket: 500 baht. Child (4–12 years): 250 baht. Guide included in price. A hard hat is mandatory inside the building and provided at the entrance.</p><h2>The Elephant Experiences</h2><p>The Sanctuary grounds include an elephant area where you can watch the elephant show and, if you choose, take an elephant ride (additional fee). The animals are resident at the venue and well cared for.</p><h2>Getting There</h2><p>The Sanctuary is 3km north of Pattaya's central beach, on Naklua Road. By car: 10 minutes from central Pattaya. Best reached by private transfer or songthaew (shared pickup truck). Admission also includes parking for 200 cars.</p><h2>How Long to Allow</h2><p>Allow a minimum of 2 hours for the guided tour and grounds. If you add the elephant show and boat trip, budget 3–4 hours total.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80',
    category: 'PATTAYA',
    tags: ['Sanctuary of Truth', 'Pattaya', 'temples', 'culture'],
    readingTimeMin: 5,
    publishedAt: date(4),
  },
  {
    slug: 'pattaya-vs-hua-hin-comparison',
    title: 'Pattaya vs Hua Hin: Which Beach Town Should You Choose?',
    excerpt: 'Both are within 2–3 hours of Bangkok, but Pattaya and Hua Hin couldn\'t be more different. Here\'s an honest comparison to help you decide.',
    content: `<h2>The Two Bangkok Escapes</h2><p>Pattaya and Hua Hin are the two most popular weekend escapes from Bangkok. Both are accessible by road in under 3 hours, but they attract very different types of travellers.</p><h2>Pattaya: The Entertainer</h2><p>Pattaya is loud, neon-lit, and always on. The beach is mediocre, but the entertainment options are outstanding: water parks, golf courses, Muay Thai, go-karts, the Sanctuary of Truth, diving, and one of Southeast Asia's most developed nightlife scenes.</p><p><strong>Best for:</strong> Groups of friends, golfers, divers, thrill-seekers, those who want endless activities.</p><h2>Hua Hin: The Retreat</h2><p>Hua Hin is the royal resort town — quiet, elegant, and family-friendly. The beach is longer and cleaner than Pattaya's. Excellent seafood restaurants, a charming night market, and a pace of life that Bangkok residents find deeply relaxing.</p><p><strong>Best for:</strong> Families, couples, those who want real beach relaxation, golfers, foodies.</p><h2>The Distance</h2><ul><li>Bangkok to Pattaya: 150km, 1.5–2 hours by private transfer</li><li>Bangkok to Hua Hin: 200km, 2.5–3 hours by private transfer</li></ul><h2>Verdict</h2><p>If you want to party and do activities, choose Pattaya. If you want to relax and eat well, choose Hua Hin. If you're travelling with young children, Hua Hin wins hands down.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
    category: 'PATTAYA',
    tags: ['Pattaya', 'Hua Hin', 'comparison', 'beach'],
    readingTimeMin: 5,
    publishedAt: date(10),
  },
  {
    slug: 'pattaya-things-to-do-guide',
    title: '15 Best Things to Do in Pattaya Beyond the Beach',
    excerpt: 'Pattaya is much more than its famous nightlife. From cultural experiences to adrenaline-pumping activities, here are 15 things to fill your days.',
    content: `<h2>Pattaya Beyond the Beach</h2><p>Most visitors come to Pattaya for the beach, but the city has diversified enormously over the past decade. You could spend a week here without stepping on the sand.</p><h2>1. Sanctuary of Truth</h2><p>The 105-metre all-wood temple on Naklua Road is Pattaya's most impressive landmark. Allow 2–3 hours.</p><h2>2. Nong Nooch Tropical Garden</h2><p>A 500-acre botanical garden with the world's largest collection of cycads, daily cultural shows, and elephant encounters. A great half-day trip.</p><h2>3. Art in Paradise</h2><p>An interactive 3D art museum where you become part of giant paintings. Great fun for families and Instagram enthusiasts.</p><h2>4. Pattaya Viewpoint</h2><p>Head up to Khao Pattaya View Point for sweeping views of the bay, especially at sunset.</p><h2>5. Tiger Park</h2><p>Walk among tigers in a licensed facility on the Sukhumvit Highway.</p><h2>6. Ramayana Water Park</h2><p>Southeast Asia's largest water park, themed around the Hindu epic. World-class slides and wave pools.</p><h2>7. Mini Siam</h2><p>Miniature replicas of famous Thai and world landmarks. Good for an hour's visit with children.</p><h2>8. Cartoon Network Amazone</h2><p>A massive Cartoon Network-themed water park near Rayong. Popular with younger children.</p><h2>9. Muay Thai Fights</h2><p>Pattaya has several dedicated Muay Thai stadiums. Fights are held most evenings and tickets start at 400 baht.</p><h2>10. Diving at Koh Larn</h2><p>Koh Larn (Coral Island), 7km offshore, has accessible dive sites suitable for beginners. Ferry from Bali Hai Pier takes 30 minutes.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    category: 'PATTAYA',
    tags: ['things to do', 'Pattaya', 'activities', 'guide'],
    readingTimeMin: 6,
    publishedAt: date(16),
  },
  {
    slug: 'bangkok-to-pattaya-transfer-guide',
    title: 'Bangkok to Pattaya: Best Ways to Get There',
    excerpt: 'Bus, private transfer, or taxi? Here\'s the honest comparison of every way to travel between Bangkok and Pattaya — and which one we recommend.',
    content: `<h2>The Bangkok–Pattaya Route</h2><p>Bangkok to Pattaya is one of Thailand's most-travelled routes — about 150km via the Motorway 7 (Bang Na–Trat Expressway). In good traffic, the journey takes 1.5 hours. During peak hours (Friday evenings, Sunday afternoons), it can stretch to 3 hours.</p><h2>Option 1: Private Transfer (Best Overall)</h2><p>Door-to-door from your Bangkok hotel or airport directly to your Pattaya hotel. Fixed price (typically 1,800–2,500 baht for a sedan, depending on pick-up location). No waiting, no stops, air-conditioned. You choose the departure time.</p><h2>Option 2: Eastern Bus Terminal (Ekamai)</h2><p>Buses depart from Ekamai Bus Terminal every 30–60 minutes from 5am to 11pm. Cost: 131 baht. Journey: 2–2.5 hours. You then need a songthaew or baht bus from Pattaya Bus Terminal to your hotel (10–40 baht).</p><h2>Option 3: Taxi from Bangkok</h2><p>A metered taxi from central Bangkok to Pattaya costs approximately 1,200–1,500 baht plus tolls. However, most Bangkok taxi drivers are unwilling to go to Pattaya by meter — they'll want to negotiate a fixed price.</p><h2>Option 4: Minibus (Khaosan Road)</h2><p>Tour companies on Khaosan Road and near Suvarnabhumi Airport offer shared minibuses at 250–350 baht per person. Multiple stops and no fixed schedule.</p><h2>Our Recommendation</h2><p>For 2+ people, a private transfer works out similar in price to the bus once you add the taxi from Pattaya terminal to your hotel — with the enormous advantage of door-to-door service.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
    category: 'PATTAYA',
    tags: ['Bangkok to Pattaya', 'transfer', 'transport', 'travel tips'],
    readingTimeMin: 5,
    publishedAt: date(25),
  },
  {
    slug: 'pattaya-golf-guide',
    title: 'Golf in Pattaya: The Best Courses and How to Book',
    excerpt: 'Pattaya is one of Asia\'s premier golf destinations with over 20 courses within an hour\'s drive. Here\'s everything a golfer needs to know.',
    content: `<h2>Pattaya's Golf Scene</h2><p>With over 20 golf courses within 60km of Pattaya, the city attracts serious golfers from Europe, Japan, Korea, and beyond. Courses range from championship layouts to fun resort tracks. Green fees are very reasonable by international standards.</p><h2>Top Courses</h2><h3>Laem Chabang International Country Club</h3><p>27 holes designed by Jack Nicklaus. Arguably the best course in the Pattaya area. Excellent condition year-round. Green fee: 2,500–3,500 baht.</p><h3>St. Andrews 2000</h3><p>18 holes with Scottish Highland-themed design. Beautiful layout, fast greens, well-maintained. Popular with European visitors. Green fee: 2,200–3,000 baht.</p><h3>Siam Country Club Waterside</h3><p>Four 9-hole courses can be combined to play 18. River-side setting with water hazards throughout. Challenging and scenic. Green fee: 2,500–3,500 baht.</p><h3>Burapha Golf & Resort</h3><p>36 holes (two 18-hole courses). Great value, quality conditions. On-site hotel and driving range. Green fee: 1,800–2,500 baht.</p><h2>Booking Tips</h2><ul><li>Book at least 2–3 days in advance in peak season (Nov–Feb)</li><li>Caddies are mandatory at most courses (cost: 300–500 baht + tip)</li><li>Rental clubs are available at all courses</li><li>Twilight rates (from 2pm) offer significant discounts</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80',
    category: 'PATTAYA',
    tags: ['golf', 'Pattaya', 'sports', 'activities'],
    readingTimeMin: 5,
    publishedAt: date(38),
  },

  // ── KRABI (5 posts) ─────────────────────────────────────────────────────────
  {
    slug: 'krabi-railay-beach-guide',
    title: 'Railay Beach Krabi: The Complete Guide to Thailand\'s Car-Free Paradise',
    excerpt: 'Accessible only by boat, Railay Beach is surrounded by towering limestone cliffs and has some of Thailand\'s most beautiful scenery. Here\'s how to get there and what to do.',
    content: `<h2>About Railay Beach</h2><p>Railay is a small peninsula in Krabi province that's cut off from the mainland by massive limestone cliffs, making it accessible only by longtail boat. This isolation has kept it undeveloped — no cars, no motorbikes, just beaches, climbing walls, and spectacular scenery.</p><h2>How to Get to Railay</h2><p>Longtail boats depart from Ao Nang Beach (15 minutes, 100 baht per person) and Krabi Town's Chao Fa Pier (45 minutes, 150 baht per person). Boats run regularly throughout the day until about 6pm, and later at night from Ao Nang.</p><h2>Railay's Four Beaches</h2><ul><li><strong>Railay West:</strong> The main swimming and sunset beach. Postcard-perfect.</li><li><strong>Railay East:</strong> Mangrove-lined, not suitable for swimming, but where most boats arrive</li><li><strong>Phra Nang Beach:</strong> Arguably the most beautiful beach in all of Thailand. A 10-minute walk from Railay West.</li><li><strong>Tonsai Beach:</strong> The rock climbers' beach. More rustic, backpacker vibe.</li></ul><h2>Rock Climbing</h2><p>Railay is one of Southeast Asia's top rock climbing destinations. The limestone cliffs have hundreds of bolted routes for all ability levels. Half-day beginners' courses start at 1,200 baht and include all equipment and instruction.</p><h2>Staying Overnight</h2><p>Several resorts operate on Railay — from the luxury Rayavadee to basic beach bungalows. Staying overnight lets you enjoy Phra Nang at sunrise, virtually alone, before the day-trippers arrive.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=80',
    category: 'KRABI',
    tags: ['Railay Beach', 'Krabi', 'beaches', 'rock climbing'],
    readingTimeMin: 6,
    publishedAt: date(6),
  },
  {
    slug: 'krabi-island-hopping-4-islands',
    title: 'Krabi Four Islands Tour: What to Expect on Thailand\'s Best Day Trip',
    excerpt: 'The Four Islands Tour is Krabi\'s most popular day trip, covering Koh Mook, Koh Chueak, Koh Waen, and Koh Ngai in one spectacular day.',
    content: `<h2>About the Four Islands</h2><p>The Four Islands tour departs from Ao Nang or Klong Jirad Pier in Krabi and visits four of the most beautiful islands in the Andaman Sea. Each island is distinct — different beaches, different coral, different character.</p><h2>The Four Islands</h2><h3>Koh Mook (Trang)</h3><p>Home to Emerald Cave — a sea cave you swim through in darkness to reach a hidden beach surrounded by jungle on all sides. Technically in Trang province but always included in the Krabi Four Islands itinerary. Only accessible at low tide.</p><h3>Koh Chueak</h3><p>A tiny island ringed by vivid coral and excellent for snorkelling. The fish are abundant and the water is crystalline.</p><h3>Koh Waen</h3><p>Also known as Chicken Island for its rock formation. Shallow turquoise water and good snorkelling around the base of the cliffs.</p><h3>Koh Ngai</h3><p>The largest of the four. Beautiful white sand beach, a small resort, and excellent reef snorkelling. Lunch is typically served here.</p><h2>Practical Information</h2><ul><li>Tours depart 8:30–9am, return 5–5:30pm</li><li>Cost: 900–1,500 baht per person including lunch</li><li>Bring reef-safe sunscreen, a change of clothes, and motion sickness tablets if prone</li><li>Best visited November–April when seas are calm</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80',
    category: 'KRABI',
    tags: ['Four Islands', 'Krabi', 'day trip', 'snorkelling', 'islands'],
    readingTimeMin: 5,
    publishedAt: date(11),
  },
  {
    slug: 'krabi-ao-nang-guide',
    title: 'Ao Nang Krabi: Your Complete Guide to the Gateway Town',
    excerpt: 'Ao Nang is Krabi\'s main beach town — the base for exploring Railay, the Four Islands, and Tiger Cave Temple. Here\'s everything you need to know.',
    content: `<h2>What Is Ao Nang?</h2><p>Ao Nang is the main tourist beach in Krabi province, 25km from Krabi Town and the departure point for boats to Railay Beach and the outlying islands. It's a busy strip of hotels, restaurants, shops, and dive centres set against a backdrop of jungle-covered limestone cliffs.</p><h2>The Beach</h2><p>Ao Nang beach itself is decent but not exceptional — fine for swimming but too busy for a truly peaceful experience. The real value of staying in Ao Nang is the access it gives you to better beaches nearby.</p><h2>Getting Around</h2><p>Ao Nang is small enough to walk end-to-end in 20 minutes. Longtail boats to Railay leave from the beach (15 minutes, 100 baht per person). For Tiger Cave Temple and Krabi Town, take a songthaew (shared pickup) along Route 4034.</p><h2>Tiger Cave Temple (Wat Tham Suea)</h2><p>The 1,237-step climb to the summit rewards you with panoramic views of Krabi's jungle, karst peaks, and Ao Nang beach below. Go early morning to avoid heat. The cave below (separate from the summit) is actually the more impressive of the two temples on site.</p><h2>Where to Eat in Ao Nang</h2><ul><li>Ruen Mai Restaurant: excellent Thai food, large portions, local prices</li><li>Carnivore Steak and Grill: popular with tourists, good steaks and burgers</li><li>Many Reasons Restaurant: rooftop views, fresh seafood</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1540914124281-342587941389?auto=format&fit=crop&w=1200&q=80',
    category: 'KRABI',
    tags: ['Ao Nang', 'Krabi', 'beaches', 'travel guide'],
    readingTimeMin: 5,
    publishedAt: date(19),
  },
  {
    slug: 'krabi-rock-climbing-guide',
    title: 'Rock Climbing in Krabi: A Beginner\'s Guide to Thailand\'s Climbing Capital',
    excerpt: 'Krabi\'s limestone karst towers are world-famous in the climbing community. Here\'s everything a first-timer needs to know about rock climbing in Thailand.',
    content: `<h2>Why Krabi is a Climbing Destination</h2><p>The limestone karst formations of Krabi province create some of the most dramatic rock climbing terrain in the world. Hundreds of bolted routes cover the cliffs at Railay, Tonsai, and Ton Sai Bay, ranging from beginner-friendly slabs to expert-level overhangs.</p><h2>The Main Climbing Areas</h2><h3>Railay East Wall</h3><p>The most accessible cliff for beginners, a short walk from the Railay boats. Routes here are well-bolted and grade from 5a to 6b. Ideal for first-timers taking a half-day introduction.</p><h3>Tonsai Beach</h3><p>More adventurous and harder to reach, Tonsai is where serious climbers stay. The routes are more challenging and the vibe is more hardcore. Routes include famous multi-pitch lines and some of Krabi's hardest sport routes.</p><h3>Diamond Cave</h3><p>A popular single-pitch crag near Railay East. Good for intermediate climbers looking for consistent 6a–7a routes.</p><h2>Taking a Beginner Course</h2><p>Most climbers in Krabi started with a half-day or full-day course. These include: equipment rental, basic technique, learning to belay, and a guided top-rope session on easy routes. Cost: 1,000–1,500 baht for a half-day. Reputable operators include King Climbers and Basecamp Tonsai.</p><h2>Best Time to Climb</h2><p>November to April is the dry season and best for climbing. May to October brings rain and high humidity — the rock stays wet and is far more dangerous. Some climbers do visit in low season but conditions are unpredictable.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1569566030073-5a91ca9c1a2a?auto=format&fit=crop&w=1200&q=80',
    category: 'KRABI',
    tags: ['rock climbing', 'Krabi', 'adventure', 'Railay', 'Tonsai'],
    readingTimeMin: 6,
    publishedAt: date(27),
  },
  {
    slug: 'krabi-travel-itinerary-7-days',
    title: '7-Day Krabi Itinerary: The Perfect Week in Southern Thailand',
    excerpt: 'A week in Krabi lets you explore beaches, islands, jungles, and temples without rushing. Here\'s a day-by-day plan for making the most of every hour.',
    content: `<h2>Day 1: Arrive in Krabi, Ao Nang</h2><p>Arrive at Krabi Airport (around noon), transfer to your hotel in Ao Nang. Afternoon: explore the beach and waterfront promenade. Sunset drinks at a rooftop bar. Dinner at Ruen Mai Restaurant.</p><h2>Day 2: Railay Beach</h2><p>Take the morning longtail boat to Railay (100 baht). Swim at Railay West, walk to Phra Nang Beach (15 minutes). Afternoon: try rock climbing with an introductory course. Sunset on Railay West before boating back.</p><h2>Day 3: Four Islands Tour</h2><p>Full day on the water. Emerald Cave on Koh Mook, snorkelling at Koh Chueak, Koh Waen, and lunch on Koh Ngai. Back by 5:30pm. Foot massage and seafood dinner in Ao Nang.</p><h2>Day 4: Tiger Cave Temple + Krabi Town</h2><p>Early start for the Tiger Cave Temple climb (1,237 steps, spectacular views). Afternoon in Krabi Town's night market (Maharaj Rd) and the weekday walking street. Try locally caught seafood.</p><h2>Day 5: Kayaking the Mangroves</h2><p>Half-day sea kayak tour through the mangrove forests of Ao Thalane. Spot monkeys, kingfishers, and mud-skippers. Afternoon: relax, swim, spa treatment.</p><h2>Day 6: Koh Lanta Day Trip</h2><p>Take a morning ferry to Koh Lanta (2 hours). A more relaxed, less touristy island than most. Rent a scooter and explore the national park, fishing villages, and west coast beaches. Return by late afternoon ferry.</p><h2>Day 7: Final Morning + Transfer</h2><p>Morning swim. Pack up. Private transfer back to Krabi Airport for your onward flight.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
    category: 'KRABI',
    tags: ['itinerary', 'Krabi', '7 days', 'travel planning'],
    readingTimeMin: 7,
    publishedAt: date(50),
  },

  // ── THAILAND (5 posts) ──────────────────────────────────────────────────────
  {
    slug: 'thailand-best-time-to-visit',
    title: 'Best Time to Visit Thailand: A Month-by-Month Guide',
    excerpt: 'Thailand\'s climate varies dramatically by region and month. Here\'s the honest, practical guide to when to visit — based on where you\'re going.',
    content: `<h2>Understanding Thailand's Climate Zones</h2><p>Thailand is roughly 1,500km from north to south and has three distinct climate zones. The north has a more temperate climate. The Gulf Coast (east coast) and the Andaman Coast (west coast) have opposite rainy seasons — so when one is wet, the other is typically dry.</p><h2>November to February: The Best Months</h2><p>This is Thailand's cool, dry season. Temperatures are comfortable (25–32°C), humidity is relatively low, and both coastlines are accessible. The downside: it's peak tourist season, so prices are higher and popular sites are busier. For first-time visitors, this is the best window.</p><h2>March to May: Hot Season</h2><p>Very hot (36–40°C in Bangkok, slightly cooler in the north). Low rainfall. The sea is beautiful on the Andaman Coast. Songkran water festival (April 13–15) is a highlight — the biggest water fight in the world. Chiang Mai in March–April suffers from agricultural burning, causing haze.</p><h2>May to October: Monsoon Season</h2><p>The southwest monsoon brings heavy rain to the Andaman Coast (Phuket, Krabi, Koh Lanta) but leaves the Gulf Coast (Koh Samui, Koh Tao) largely dry until October–November. Bangkok and Chiang Mai receive significant but manageable rain.</p><h2>Regional Guide</h2><ul><li><strong>Bangkok:</strong> Best Nov–Feb</li><li><strong>Chiang Mai:</strong> Best Nov–Feb; avoid March–April smoke season</li><li><strong>Phuket/Krabi:</strong> Best Nov–April</li><li><strong>Koh Samui:</strong> Best Feb–Sep; avoids the Gulf monsoon</li><li><strong>Koh Tao:</strong> Best March–September</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80',
    category: 'THAILAND',
    tags: ['travel planning', 'Thailand', 'climate', 'when to visit'],
    readingTimeMin: 7,
    publishedAt: date(1),
  },
  {
    slug: 'thailand-first-time-visitor-guide',
    title: 'First Time in Thailand? Read This Before You Go',
    excerpt: 'Visas, currency, transport, culture, food, safety — here\'s the comprehensive first-timer\'s guide to Thailand, written for travellers who\'ve never been before.',
    content: `<h2>Visas</h2><p>Most Western nationalities (UK, EU, USA, Australia, Canada) receive a 30-day visa exemption on arrival in Thailand — no visa required. Extensions are possible at an Immigration Office for 1,900 baht. For longer stays, consider a Tourist Visa (60 days + 30 day extension) from a Thai embassy before travel.</p><h2>Currency</h2><p>Thai Baht (THB). At time of writing: £1 ≈ 44 baht, $1 ≈ 35 baht. Use ATMs for cash (best rates; 220 baht fee per withdrawal from most machines). Credit cards accepted at hotels and restaurants but not at markets or street stalls.</p><h2>Transport Between Cities</h2><p>Domestic flights are excellent value (often 500–1,500 baht). Overnight trains are comfortable and an experience in themselves. Private road transfers are the best option for shorter distances (Bangkok to Pattaya, Phuket to Krabi).</p><h2>Mobile Data</h2><p>Buy a tourist SIM at the airport on arrival. DTAC and True Move both offer 15-day cards with 30GB of data for around 299 baht. Far better than roaming.</p><h2>Food Safety</h2><p>Thai street food is overwhelmingly safe. Look for stalls with high turnover. Avoid places with flies or that look like they haven't been cleaned. Ice is generally safe in restaurants; avoid ice from street stalls if you have a sensitive stomach.</p><h2>Cultural Notes</h2><ul><li>Remove shoes before entering temples and Thai homes</li><li>Dress modestly at temples — cover shoulders and knees</li><li>The monarchy is sacred — never disparage the royal family</li><li>Loud confrontation is deeply impolite in Thai culture</li><li>Wai greeting: press palms together and bow slightly</li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1200&q=80',
    category: 'THAILAND',
    tags: ['first time', 'Thailand', 'travel tips', 'beginner guide'],
    readingTimeMin: 8,
    publishedAt: date(9),
  },
  {
    slug: 'thailand-budget-travel-guide',
    title: 'Thailand on a Budget: How to Travel Well for £30–£50/Day',
    excerpt: 'Thailand can be done incredibly cheaply without sacrificing comfort or experiences. Here\'s a realistic breakdown of costs and how to keep them low.',
    content: `<h2>Is Thailand Still a Budget Destination?</h2><p>Thailand has become more expensive over the past decade, but it remains one of the best-value travel destinations in Asia. With careful planning, you can travel comfortably for £30–50/day — or splash out on luxury for what budget accommodation costs in London.</p><h2>Accommodation: £8–£40/night</h2><ul><li>Backpacker dorm: £5–10</li><li>Private guesthouse room: £15–25</li><li>Boutique hotel: £30–60</li><li>4-star resort: £60–150</li></ul><h2>Food: £5–£20/day</h2><p>Eat street food and local restaurants to spend £5–8/day on three meals. A curry and rice from a local shop costs 50–80 baht (£1–£1.80). Western restaurants and hotel dining cost 3–5x more.</p><h2>Transport: £2–£15/day</h2><p>BTS/MRT in Bangkok: 16–59 baht per trip. Songthaew (shared pickup): 10–50 baht. Inter-city bus: 100–300 baht. Private transfers: 1,200–3,000 baht for airport-to-hotel.</p><h2>Activities: £5–£40/day</h2><p>Temple entrance fees: free to 500 baht. Muay Thai fight: 400–1,000 baht. Scuba diving day trip: 1,800–2,500 baht. Thai massage: 250–500 baht/hour.</p><h2>Sample Daily Budget</h2><ul><li>Street food breakfast + lunch + dinner: 150 baht</li><li>BTS/transport: 60 baht</li><li>One major attraction: 300 baht</li><li>Accommodation (guesthouse): 600 baht</li><li>Drinks/snacks: 100 baht</li><li><strong>Total: ~1,210 baht (~£27)</strong></li></ul>`,
    featuredImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    category: 'THAILAND',
    tags: ['budget travel', 'Thailand', 'money', 'backpacking'],
    readingTimeMin: 6,
    publishedAt: date(15),
  },
  {
    slug: 'thailand-national-parks-guide',
    title: 'Best National Parks in Thailand for Nature Lovers',
    excerpt: 'Thailand has 157 national parks covering 19% of the country. These are the most spectacular ones for wildlife, trekking, and natural scenery.',
    content: `<h2>Thailand's Protected Nature</h2><p>Thailand's national park system protects some of Southeast Asia's most biodiverse landscapes — from the cloud forests of the north to the coral reefs of the Andaman Sea. With 157 national parks, there's more wild Thailand than most visitors realise.</p><h2>Khao Yai National Park</h2><p>UNESCO World Heritage Site, 2 hours from Bangkok. Home to Asian elephants, gibbons, Siamese firebacks, and hornbills. The 2,165 sq km park has well-marked trails and night safari tours. Best visited October–May.</p><h2>Doi Inthanon National Park</h2><p>Chiang Mai province. Home to Thailand's highest peak (2,565m). Twin royal pagodas, stunning waterfalls, and excellent birdwatching. Often cold at the summit in winter — bring layers.</p><h2>Erawan National Park</h2><p>Kanchanaburi province, 3 hours from Bangkok. The seven-tiered emerald waterfall is one of Thailand's most beautiful natural features. Swim in the clear pools between tiers. Can be crowded on weekends.</p><h2>Similan Islands Marine National Park</h2><p>Nine islands in the Andaman Sea, rated among the world's top 10 dive sites. Exceptional visibility, whale sharks, manta rays, and pristine coral. Open November–April only.</p><h2>Kaeng Krachan National Park</h2><p>Thailand's largest national park, near Hua Hin. Very good for wildlife spotting — elephants, Asiatic black bears, leopards, and over 400 bird species.</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
    category: 'THAILAND',
    tags: ['national parks', 'nature', 'wildlife', 'Thailand'],
    readingTimeMin: 6,
    publishedAt: date(33),
  },
  {
    slug: 'thailand-transport-complete-guide',
    title: 'Getting Around Thailand: Complete Transport Guide 2025',
    excerpt: 'From Bangkok\'s BTS to overnight trains and private transfers — here\'s every way to get around Thailand, with honest advice on which to use when.',
    content: `<h2>The Key Transport Options</h2><p>Thailand has a well-developed transport network, but choosing the right option for each journey can be confusing. Here's a practical breakdown of every method and when to use it.</p><h2>Bangkok Public Transport</h2><ul><li><strong>BTS Skytrain:</strong> The best way to get around central Bangkok. Fast, air-conditioned, 16–59 baht per trip. Covers Sukhumvit, Silom, and Chatuchak.</li><li><strong>MRT (Metro):</strong> Complements the BTS. Good for Lumphini, Chatuchak, and Rattanakosin areas.</li><li><strong>Chao Phraya Express Boat:</strong> Tourist and local boats along the river. 15 baht (orange flag) to 60 baht (tourist boat). Great for accessing riverside temples.</li><li><strong>Metered Taxi:</strong> Cheaper than ride-hailing for short distances. Always insist on the meter.</li><li><strong>Grab:</strong> Thailand's equivalent of Uber. Fixed price, no negotiation, clean cars.</li></ul><h2>Inter-City Transport</h2><ul><li><strong>Domestic Flights:</strong> Bangkok to Phuket or Chiang Mai: £10–30. Book through Thai Airways, AirAsia, Nok Air, Lion Air.</li><li><strong>Overnight Trains:</strong> Bangkok to Chiang Mai (sleeper): 600–1,400 baht. Comfortable, scenic, saves accommodation cost. Book at Hua Lamphong Station or online.</li><li><strong>Intercity Bus:</strong> Cheap and reliable. Bangkok to Phuket: 600–900 baht (10 hours). Bangkok to Chiang Mai: 500–800 baht (9 hours).</li><li><strong>Private Transfer:</strong> Best for shorter distances (up to 4 hours). Door-to-door, flexible timing, no stops. Werest covers major routes across Thailand.</li></ul><h2>Island Transport</h2><p>Ferries connect the mainland to major islands. High-speed boats are faster but rougher — choose based on weather conditions. Car ferries are available to larger islands (Koh Samui, Koh Chang).</p>`,
    featuredImage: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=80',
    category: 'THAILAND',
    tags: ['transport', 'Thailand', 'getting around', 'travel tips'],
    readingTimeMin: 7,
    publishedAt: date(42),
  },
];

async function main() {
  console.log('🌱 Seeding 30 blog posts...');

  // Delete existing blog posts to avoid duplicates
  await prisma.blogPost.deleteMany({});
  console.log('🗑  Cleared existing blog posts');

  for (const post of POSTS) {
    await prisma.blogPost.create({
      data: {
        slug:          post.slug,
        title:         post.title,
        excerpt:       post.excerpt,
        content:       post.content,
        featuredImage: post.featuredImage,
        category:      post.category as 'BANGKOK' | 'PATTAYA' | 'THAILAND' | 'PHUKET' | 'KRABI',
        tags:          post.tags,
        status:        'PUBLISHED',
        publishedAt:   new Date(post.publishedAt),
        readingTimeMin: post.readingTimeMin,
        authorName:    'Werest Travel',
        authorTitle:   'Travel Expert',
      },
    });
    console.log(`  ✓ ${post.title}`);
  }

  console.log(`\n✅ Seeded ${POSTS.length} blog posts successfully!`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
